@Api_HostAddress = http://localhost:5074
@taskId = 25d0987e-fcff-41fc-b293-4e5611f4069e

### OpenApi
GET {{Api_HostAddress}}/openapi/v1.json

### GetTasks
GET {{Api_HostAddress}}/tasks/
Accept: application/json

### GetTasksSummary
GET {{Api_HostAddress}}/tasks/summary
Accept: application/json

### CreateTaskItem
POST {{Api_HostAddress}}/tasks/
Content-Type: application/json

{
    "TaskId": "{{taskId}}",
    "Title": "Some Task 123465"
}

### Increase Priority
PUT {{Api_HostAddress}}/tasks/{{taskId}}/priority/increase
Accept: application/json

### GetTaskDetail
GET {{Api_HostAddress}}/tasks/{{taskId}}
Accept: application/json

### CompleteTaskItem
PUT {{Api_HostAddress}}/tasks/{{taskId}}/complete
Accept: application/json

### DeleteTaskItem
DELETE {{Api_HostAddress}}/tasks/{{taskId}}
Accept: application/json
